FFMPEG_INSTALL_DIR=${PWD}/build/Release/x86_64-linux/FFmpeg/install
FFMPEG_INC_DIR=${FFMPEG_INSTALL_DIR}/include
FFMPEG_LIB_DIR=${FFMPEG_INSTALL_DIR}/lib

JPEG_TRUBO_INSTALL_DIR=${PWD}/build/Release/x86_64-linux/libjpeg-turbo/install
JPEG_TRUBO_INC_DIR=${JPEG_TRUBO_INSTALL_DIR}/include
JPEG_TRUBO_LIB_DIR=${JPEG_TRUBO_INSTALL_DIR}/lib

export PATH=${FFMPEG_INSTALL_DIR}/bin:${JPEG_TRUBO_INSTALL_DIR}/bin:${PATH}
export CPATH="${FFMPEG_INC_DIR}:${JPEG_TRUBO_INC_DIR}:$CPATH"
export LD_LIBRARY_PATH="${FFMPEG_LIB_DIR}:${JPEG_TRUBO_LIB_DIR}:$LD_LIBRARY_PATH"
export LIBRARY_PATH="${FFMPEG_LIB_DIR}:${JPEG_TRUBO_LIB_DIR}:$LIBRARY_PATH"